### ISSUE TITLE
symfony 4, missing rabbitmq commands from console

### ISSUE THREAD

**Issue by mkingbe** [php-amqplib/RabbitMqBundle#502] opened 2017-12-07 10:19 UTC
Hello, 

I just upgraded a project to symfony 4 and I see that the rabbitmq commands are missing from console.

How can I enable them ?

**Comment by stloyd** [comment] 2017-12-07 10:37
Closing as duplicate of #501 .

**Closed by stloyd** 2017-12-07 10:37 UTC
