### ISSUE TITLE
The DataCollector does not work with lazy connection

### ISSUE THREAD

**Issue by 1ed** [php-amqplib/RabbitMqBundle#478] opened 2017-10-02 08:03 UTC
```
Symfony\Component\Debug\Exception\FatalThrowableError:
Call to a member function debug_method_signature1() on null

  at vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:485
  at PhpAmqpLib\Connection\AbstractConnection->prepare_channel_method_frame(1, array(20, 10), '' . "\0" . '', object(AMQPWriter))
     (vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:452)
  at PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, array(20, 10), object(AMQPWriter))
     (vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:230)
  at PhpAmqpLib\Channel\AbstractChannel->send_method_frame(array(20, 10), object(AMQPWriter))
     (vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:256)
  at PhpAmqpLib\Channel\AMQPChannel->x_open()
     (vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:107)
  at PhpAmqpLib\Channel\AMQPChannel->__construct(object(AMQPLazyConnection))
     (var/cache/dev/appDevDebugProjectContainer.php:3388)
  at appDevDebugProjectContainer->getOldSoundRabbitMq_Channel_RealTimeHifiService()
     (var/cache/dev/appDevDebugProjectContainer.php:1778)
  at appDevDebugProjectContainer->getOldSoundRabbitMq_DataCollectorService()
     (vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:335)
  at Symfony\Component\DependencyInjection\Container->get('old_sound_rabbit_mq.data_collector')
     (var/cache/dev/appDevDebugProjectContainer.php:1861)
  at appDevDebugProjectContainer->getProfilerService()
     (vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:335)
  at Symfony\Component\DependencyInjection\Container->get('profiler')
     (var/cache/dev/appDevDebugProjectContainer.php:1874)
  at appDevDebugProjectContainer->getProfilerListenerService()
     (vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:335)
  at Symfony\Component\DependencyInjection\Container->get('profiler_listener')
     (var/cache/dev/appDevDebugProjectContainer.php:750)
  at appDevDebugProjectContainer->{closure}()
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:229)
  at Symfony\Component\EventDispatcher\EventDispatcher->sortListeners('kernel.response')
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:61)
  at Symfony\Component\EventDispatcher\EventDispatcher->getListeners('kernel.response')
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:142)
  at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->getListeners('kernel.response')
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:252)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->preProcess('kernel.response')
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:141)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.response', object(FilterResponseEvent))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:193)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(Response), object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:175)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:24)
```

**Comment by nick4fake** [comment] 2018-01-30 12:44
Duplicate of https://github.com/php-amqplib/RabbitMqBundle/issues/195?

**Closed** 2021-04-06 16:49 UTC
Labels: no-issue-activity
