### ISSUE TITLE
Consumer performance drops continuously

### ISSUE THREAD

**Issue by andreasferber** [php-amqplib/RabbitMqBundle#144] opened 2013-11-22 11:46 UTC
Same as issue #82, the performance of consumers drops sharply while running. Right after starting my consumer it processes about 40 messages per second, but this drops off to about 20/s after a minute, and decreases further from there. It seems to level off at 9-10/s, however I think I have also seen a consumer processing less than 1/s ater running for a day or two. This all while running with 100% CPU usage all the time.

It is NOT a QOS issue, I tried different combinations of settings already.

**Comment by calumbrodie** [comment] 2015-03-25 14:20
Does the consumer fork the process when handling jobs? If not how does it avoid memory use increasing (due to use of logger for example?). I'm also seeing memory use increasing over time and having to use a small number of jobs with my supervisor to work round this issue.

**Comment by castarco** [comment] 2015-07-29 08:21
@calumbrodie , doesn't release resources the logger until the process is finished?

I think it's important to link particular cases to help developers reproducing the "error", or to close this issue if there is no empiric evidence supporting those statements...

**Comment by calumbrodie** [comment] 2015-07-29 09:28
It was a question.

**Closed** 2021-03-27 10:10 UTC
Labels: Question, no-issue-activity
